# Generated by Django 5.0 on 2026-02-21 10:36

import apps.visa_applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EVisa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visa_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de visa"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Date d'émission")),
                ("expiry_date", models.DateField(verbose_name="Date d'expiration")),
                ("qr_code", models.TextField(verbose_name="QR Code (base64)")),
                (
                    "pdf_file",
                    models.FileField(upload_to="evisas/", verbose_name="Fichier PDF"),
                ),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="Révoqué"),
                ),
                ("revocation_date", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "e-Visa",
                "verbose_name_plural": "e-Visas",
                "db_table": "evisa_evisa",
            },
        ),
        migrations.CreateModel(
            name="VisaType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(verbose_name="Validité (jours)"),
                ),
                (
                    "max_stay_days",
                    models.PositiveIntegerField(
                        verbose_name="Durée séjour max (jours)"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Frais (XAF)"
                    ),
                ),
                (
                    "required_documents",
                    models.JSONField(default=list, verbose_name="Documents requis"),
                ),
                (
                    "processing_time_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Délai traitement (jours)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de visa",
                "verbose_name_plural": "Types de visa",
                "db_table": "evisa_visa_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BorderCrossing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "crossing_type",
                    models.CharField(
                        choices=[("ENTRY", "Entrée"), ("EXIT", "Sortie")], max_length=10
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Point de passage"),
                ),
                ("crossing_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "border_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="border_crossings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evisa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crossings",
                        to="visa_applications.evisa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passage frontière",
                "verbose_name_plural": "Passages frontières",
                "db_table": "evisa_border_crossing",
                "ordering": ["-crossing_date"],
            },
        ),
        migrations.CreateModel(
            name="VisaApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de demande"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumise"),
                            ("PROCESSING", "En traitement"),
                            ("PENDING_DOCS", "Attente documents"),
                            ("PENDING_REVIEW", "Attente avis consulaire"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nom complet"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                (
                    "place_of_birth",
                    models.CharField(max_length=100, verbose_name="Lieu de naissance"),
                ),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Nationalité"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Masculin"),
                            ("FEMALE", "Féminin"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=10,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(max_length=50, verbose_name="Numéro passeport"),
                ),
                (
                    "passport_issue_date",
                    models.DateField(verbose_name="Date émission passeport"),
                ),
                (
                    "passport_expiry_date",
                    models.DateField(verbose_name="Date expiration passeport"),
                ),
                (
                    "passport_country",
                    models.CharField(max_length=100, verbose_name="Pays émission"),
                ),
                ("purpose_of_visit", models.TextField(verbose_name="Motif de visite")),
                (
                    "arrival_date",
                    models.DateField(verbose_name="Date d'arrivée prévue"),
                ),
                (
                    "departure_date",
                    models.DateField(verbose_name="Date de départ prévue"),
                ),
                (
                    "address_in_cameroon",
                    models.TextField(verbose_name="Adresse au Cameroun"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Soumis le"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Traité le"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Motif de rejet"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent assigné",
                    ),
                ),
                (
                    "visa_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="visa_applications.visatype",
                        verbose_name="Type de visa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de visa",
                "verbose_name_plural": "Demandes de visa",
                "db_table": "evisa_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="evisa",
            name="application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evisa",
                to="visa_applications.visaapplication",
                verbose_name="Demande",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "Passeport"),
                            ("PHOTO", "Photo d'identité"),
                            ("TRAVEL_ITINERARY", "Itinéraire de voyage"),
                            ("ACCOMMODATION_PROOF", "Justificatif d'hébergement"),
                            ("FINANCIAL_PROOF", "Justificatif financier"),
                            ("INVITATION_LETTER", "Lettre d'invitation"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.visa_applications.models.document_upload_path,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="Taille (octets)"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Type MIME"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="visa_applications.visaapplication",
                        verbose_name="Demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "evisa_document",
            },
        ),
        migrations.CreateModel(
            name="ApplicationComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True, verbose_name="Commentaire interne"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="visa_applications.visaapplication",
                        verbose_name="Demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "db_table": "evisa_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(
                fields=["applicant", "status"], name="evisa_appli_applica_401443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(
                fields=["application_number"], name="evisa_appli_applica_baa3d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visaapplication",
            index=models.Index(
                fields=["status", "submitted_at"], name="evisa_appli_status_12a1a2_idx"
            ),
        ),
    ]
