# Generated by Django 5.0 on 2026-02-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visa_applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evisa",
            name="application",
        ),
        migrations.DeleteModel(
            name="BorderCrossing",
        ),
        migrations.DeleteModel(
            name="EVisa",
        ),
    ]
