# Generated by Django 5.0 on 2026-03-27 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0002_remove_evisa_application_delete_bordercrossing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EVisa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visa_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('qr_code_data', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='e_visas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-Visa émis',
                'db_table': 'evisa_issued',
            },
        ),
        migrations.CreateModel(
            name='VisaHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique',
                'db_table': 'evisa_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='border_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='border_checks', to=settings.AUTH_USER_MODEL, verbose_name='Agent frontière'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='border_check_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Non vérifié'), ('ENTERED', 'Entrée enregistrée'), ('EXITED', 'Sortie enregistrée')], default='NOT_CHECKED', max_length=20, verbose_name='Statut frontière'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='border_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date vérification frontière'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='embassy_comment',
            field=models.TextField(blank=True, verbose_name='Commentaire ambassade'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='embassy_opinion',
            field=models.CharField(choices=[('NONE', 'Aucun avis'), ('FAVORABLE', 'Favorable'), ('UNFAVORABLE', 'Défavorable')], default='NONE', max_length=20, verbose_name='Avis ambassade'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='has_biometrics',
            field=models.BooleanField(default=False, verbose_name='Biométrie vérifiée'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='residence_country',
            field=models.CharField(default='Autre', max_length=100, verbose_name='Pays de résidence'),
        ),
        migrations.AddIndex(
            model_name='visaapplication',
            index=models.Index(fields=['residence_country'], name='evisa_appli_residen_c0976f_idx'),
        ),
        migrations.AddField(
            model_name='evisa',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='e_visa', to='visa_applications.visaapplication'),
        ),
        migrations.AddField(
            model_name='visahistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='visa_applications.visaapplication'),
        ),
        migrations.AddField(
            model_name='visahistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
