# Generated by Django 5.0 on 2026-03-30 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "visa_applications",
            "0003_evisa_visahistory_visaapplication_border_agent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="visaapplication",
            name="birth_country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Pays de naissance"
            ),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Contact d'urgence (Nom)",
            ),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Contact d'urgence (Tél)",
            ),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="marital_status",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Situation matrimoniale",
            ),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="profession",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Profession"
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="border_check_status",
            field=models.CharField(
                choices=[
                    ("NOT_CHECKED", "Non vérifié"),
                    ("ENTERED", "Entrée enregistrée"),
                    ("EXITED", "Sortie enregistrée"),
                    ("DENIED", "Entrée refusée"),
                ],
                default="NOT_CHECKED",
                max_length=20,
                verbose_name="Statut frontière",
            ),
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HIGH", "Haute"),
                            ("MEDIUM", "Moyenne"),
                            ("LOW", "Basse"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_alerts",
                        to="visa_applications.visaapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte de sécurité",
                "verbose_name_plural": "Alertes de sécurité",
                "db_table": "evisa_security_alert",
                "ordering": ["-created_at"],
            },
        ),
    ]
