# Generated by Django 5.0 on 2026-04-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0005_visaapplication_last_completed_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVisa',
        ),
    ]
