# Generated by Django 5.0 on 2026-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0006_delete_evisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumise'), ('PROCESSING', 'En traitement'), ('PENDING_DOCS', 'Attente documents'), ('DOCS_PROVIDED', 'Compléments fournis'), ('PENDING_REVIEW', 'Attente avis consulaire'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
    ]
