# Generated by Django 5.0 on 2026-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0007_alter_visaapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='group_reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Référence de groupe'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='is_group_primary',
            field=models.BooleanField(default=False, verbose_name='Demandeur principal du groupe'),
        ),
    ]
