# Generated by Django 5.0.1 on 2026-04-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0008_visaapplication_group_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Signalé (Watchlist)'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='security_notes',
            field=models.TextField(blank=True, verbose_name='Notes de sécurité'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='security_risk',
            field=models.CharField(default='LOW', max_length=20, verbose_name='Niveau de risque'),
        ),
    ]
