# Generated by Django 5.0 on 2026-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0009_visaapplication_is_flagged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='address_in_cameroon',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse au Cameroun'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée prévue"),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de départ prévue'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Masculin'), ('FEMALE', 'Féminin'), ('OTHER', 'Autre')], max_length=10, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays émission'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date expiration passeport'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date émission passeport'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro passeport'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='purpose_of_visit',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de visite'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='residence_country',
            field=models.CharField(blank=True, default='Autre', max_length=100, null=True, verbose_name='Pays de résidence'),
        ),
    ]
