# Generated by Django 5.0.1 on 2026-04-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0010_alter_visaapplication_address_in_cameroon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom complet'),
        ),
    ]
