# Generated by Django 5.0.1 on 2026-05-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0011_alter_visaapplication_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CNI / ID National'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='processing_type',
            field=models.CharField(choices=[('STANDARD', 'Standard (72 heures)'), ('EXPRESS', 'Express (24 heures)')], default='STANDARD', max_length=20, verbose_name='Type de traitement'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passeport'), ('PHOTO', "Photo d'identité"), ('TRAVEL_ITINERARY', 'Billet Avion / Titre Transport'), ('ACCOMMODATION_PROOF', "Justificatif d'hébergement"), ('FINANCIAL_PROOF', 'Justificatif Financier / Subsistance'), ('VACCINATION_CERT', 'Carnet de vaccination'), ('DESTINATION_VISA', 'Visa pays destination'), ('MISSION_ORDER', 'Ordre de mission'), ('RESIDENCE_CERT', 'Certificat de domicile'), ('PROFESSION_PROOF', 'Justificatif de profession'), ('REPATRIATION_GUAR', 'Garantie de rapatriement'), ('STUDENT_REG', "Attestation d'inscription scolaire"), ('INTERNSHIP_ATT', 'Attestation de mise en stage'), ('WORK_CONTRACT', 'Contrat de travail'), ('PROFESSION_AUTH', "Autorisation d'exercer / Promouvoir"), ('FAMILY_ACT', 'Acte de mariage / Parental'), ('VERBAL_NOTE', 'Note verbale'), ('IDENTITY_CARD', "Carte Nationale d'Identité"), ('OTHER', 'Autre')], max_length=30, verbose_name='Type de document'),
        ),
    ]
