# Generated by Django 5.0 on 2026-05-12 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0012_visaapplication_national_id_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passeport'), ('PHOTO', "Photo d'identité"), ('TRAVEL_ITINERARY', 'Billet Avion / Titre Transport'), ('ACCOMMODATION_PROOF', "Justificatif d'hébergement"), ('FINANCIAL_PROOF', 'Justificatif Financier / Subsistance'), ('VACCINATION_CERT', 'Carnet de vaccination'), ('DESTINATION_VISA', 'Visa pays destination'), ('MISSION_ORDER', 'Ordre de mission'), ('RESIDENCE_CERT', 'Certificat de domicile'), ('PROFESSION_PROOF', 'Justificatif de profession'), ('REPATRIATION_GUAR', 'Garantie de rapatriement'), ('STUDENT_REG', "Attestation d'inscription scolaire"), ('INTERNSHIP_ATT', 'Attestation de mise en stage'), ('WORK_CONTRACT', 'Contrat de travail'), ('PROFESSION_AUTH', "Autorisation d'exercer / Promouvoir"), ('FAMILY_ACT', 'Acte de mariage / Parental'), ('VERBAL_NOTE', 'Note verbale'), ('IDENTITY_CARD', "Carte Nationale d'Identité"), ('EXTENSION_PROOF', 'Justificatif de prorogation'), ('OTHER', 'Autre')], max_length=30, verbose_name='Type de document'),
        ),
        migrations.CreateModel(
            name='StayExtensionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_expiry_date', models.DateField(verbose_name="Date d'expiration actuelle")),
                ('requested_days', models.PositiveIntegerField(verbose_name='Nombre de jours demandés')),
                ('new_expiry_date', models.DateField(verbose_name="Nouvelle date d'expiration prévue")),
                ('reason', models.TextField(verbose_name='Motif de la demande')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Soumise'), ('PROCESSING', 'En traitement'), ('PENDING_PAYMENT', 'En attente de paiement'), ('PAID', 'Payée'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée'), ('CANCELLED', 'Annulée')], default='SUBMITTED', max_length=20, verbose_name='Statut')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('payment_status', models.CharField(default='PENDING', max_length=20, verbose_name='Statut du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_extensions', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_extensions', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné')),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='visa_applications.visaapplication', verbose_name="Demande de visa d'origine")),
            ],
            options={
                'verbose_name': 'Demande de prorogation',
                'verbose_name_plural': 'Demandes de prorogation',
                'db_table': 'evisa_stay_extension',
                'ordering': ['-created_at'],
            },
        ),
    ]
