# Generated by Django 5.0.1 on 2026-05-17 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0013_alter_document_document_type_stayextensionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de demande original')),
                ('original_application_id', models.UUIDField(verbose_name='ID Original')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email demandeur')),
                ('status', models.CharField(max_length=20, verbose_name='Statut final')),
                ('snapshot_data', models.JSONField(verbose_name='Données complètes (Immuable)')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'archivage")),
                ('retention_end_date', models.DateTimeField(verbose_name='Fin de période de rétention légale')),
            ],
            options={
                'verbose_name': 'Demande Archivée',
                'verbose_name_plural': 'Demandes Archivées',
                'db_table': 'evisa_archived_application',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.AddField(
            model_name='stayextensionrequest',
            name='extension_proof',
            field=models.FileField(blank=True, null=True, upload_to='extensions/', verbose_name='Justificatif de prorogation'),
        ),
        migrations.AddField(
            model_name='stayextensionrequest',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de prorogation'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='biometric_liveness_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score Liveness (%)'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='biometric_liveness_status',
            field=models.CharField(default='PENDING', max_length=20, verbose_name='Statut Biométrie'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='live_photo',
            field=models.ImageField(blank=True, null=True, upload_to='biometrics/live/', verbose_name='Photo en direct (Liveness)'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Numéro CNI / ID National (Chiffré)'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='passport_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Numéro passeport (Chiffré)'),
        ),
    ]
