# Generated by Django 5.0.1 on 2026-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa_applications', '0014_archivedapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passeport'), ('PHOTO', "Photo d'identité"), ('TRAVEL_ITINERARY', 'Billet Avion / Titre Transport'), ('ACCOMMODATION_PROOF', "Justificatif d'hébergement"), ('FINANCIAL_PROOF', 'Justificatif Financier / Subsistance'), ('VACCINATION_CERT', 'Carnet de vaccination'), ('DESTINATION_VISA', 'Visa pays destination'), ('MISSION_ORDER', 'Ordre de mission'), ('RESIDENCE_CERT', 'Certificat de domicile'), ('PROFESSION_PROOF', 'Justificatif de profession'), ('REPATRIATION_GUAR', 'Garantie de rapatriement'), ('STUDENT_REG', "Attestation d'inscription scolaire"), ('INTERNSHIP_ATT', 'Attestation de mise en stage'), ('WORK_CONTRACT', 'Contrat de travail'), ('PROFESSION_AUTH', "Autorisation d'exercer / Promouvoir"), ('FAMILY_ACT', 'Acte de mariage / Parental'), ('INVITATION_LETTER', "Lettre d'invitation"), ('VERBAL_NOTE', 'Note verbale'), ('IDENTITY_CARD', "Carte Nationale d'Identité"), ('EXTENSION_PROOF', 'Justificatif de prorogation'), ('OTHER', 'Autre')], max_length=30, verbose_name='Type de document'),
        ),
    ]
