# Generated by Django 5.0 on 2026-03-23 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Code unique')),
                ('type', models.CharField(choices=[('AUTH', 'Authentification'), ('APPLICATION', 'Dossier Visa'), ('SECURITY', 'Sécurité'), ('PAYMENT', 'Paiement'), ('SYSTEM', 'Système')], default='SYSTEM', max_length=20)),
                ('subject', models.CharField(max_length=255, verbose_name="Sujet de l'email")),
                ('body_text', models.TextField(verbose_name="Corps de l'email (texte brut)")),
                ('body_html', models.TextField(blank=True, verbose_name="Corps de l'email (HTML)")),
                ('language', models.CharField(default='FR', max_length=10, verbose_name='Langue')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Modèle d'email",
                'verbose_name_plural': "Modèles d'emails",
                'db_table': 'email_template',
                'ordering': ['type', 'name'],
            },
        ),
    ]
