# Generated by Django 5.0 on 2026-02-23 14:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "visa_applications",
            "0002_remove_evisa_application_delete_bordercrossing_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EVisa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "visa_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de visa"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Date d'émission")),
                ("expiry_date", models.DateField(verbose_name="Date d'expiration")),
                ("qr_code", models.TextField(verbose_name="QR Code")),
                (
                    "pdf_file_path",
                    models.CharField(max_length=500, verbose_name="Chemin du PDF"),
                ),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="Révoqué"),
                ),
                (
                    "revocation_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de révocation"
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motif de révocation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evisa",
                        to="visa_applications.visaapplication",
                        verbose_name="Demande de visa",
                    ),
                ),
            ],
            options={
                "verbose_name": "e-Visa",
                "verbose_name_plural": "e-Visas",
                "db_table": "e_visa",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BorderCrossing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "crossing_type",
                    models.CharField(
                        choices=[("ENTRY", "Entrée"), ("EXIT", "Sortie")],
                        max_length=10,
                        verbose_name="Type (Entrée/Sortie)",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Point de passage"),
                ),
                (
                    "crossing_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date et heure"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "border_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evisa_border_crossings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent frontière",
                    ),
                ),
                (
                    "evisa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crossings",
                        to="evisa.evisa",
                        verbose_name="e-Visa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passage Frontière",
                "verbose_name_plural": "Passages Frontière",
                "db_table": "border_crossing",
                "ordering": ["-crossing_date"],
            },
        ),
        migrations.AddIndex(
            model_name="evisa",
            index=models.Index(
                fields=["visa_number"], name="e_visa_visa_nu_1d5766_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evisa",
            index=models.Index(
                fields=["expiry_date"], name="e_visa_expiry__c8d757_idx"
            ),
        ),
    ]
