# Generated by Django 5.0 on 2026-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Clé de configuration')),
                ('value', models.TextField(blank=True, verbose_name='Valeur')),
                ('category', models.CharField(choices=[('GENERAL', 'Général'), ('EMAIL', 'Serveur Email'), ('PAYMENT', 'Paiement'), ('SECURITY', 'Sécurité')], default='GENERAL', max_length=50, verbose_name='Catégorie')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre Système',
                'verbose_name_plural': 'Paramètres Système',
                'db_table': 'system_setting',
                'ordering': ['category', 'key'],
            },
        ),
    ]
