# Generated by Django 5.0 on 2026-03-23 18:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisa', '0002_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('UNREAD', 'Non lu'), ('READ', 'Lu'), ('REPLIED', 'Répondu')], default='UNREAD', max_length=10, verbose_name='Statut')),
                ('reply_message', models.TextField(blank=True, null=True, verbose_name='Message de réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_messages', to=settings.AUTH_USER_MODEL, verbose_name='Répondu par')),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'db_table': 'contact_message',
                'ordering': ['-created_at'],
            },
        ),
    ]
