# Generated by Django 5.0 on 2026-04-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisa', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordercrossing',
            name='expected_exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie prévue'),
        ),
        migrations.AddField(
            model_name='bordercrossing',
            name='linked_exit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_entry', to='evisa.bordercrossing', verbose_name='Sortie liée'),
        ),
    ]
