# Generated by Django 5.0 on 2026-04-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisa', '0004_bordercrossing_expected_exit_date_and_more'),
        ('visa_applications', '0007_alter_visaapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordercrossing',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='border_crossings', to='visa_applications.visaapplication', verbose_name='Demande de visa'),
        ),
        migrations.AlterField(
            model_name='bordercrossing',
            name='crossing_type',
            field=models.CharField(choices=[('ENTRY', 'Entrée'), ('EXIT', 'Sortie'), ('DENIED', 'Refus Entrée')], max_length=10, verbose_name='Type (Entrée/Sortie/Refus)'),
        ),
        migrations.AlterField(
            model_name='bordercrossing',
            name='evisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crossings', to='evisa.evisa', verbose_name='e-Visa'),
        ),
    ]
