# Generated by Django 5.0.1 on 2026-04-25 18:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evisa', '0005_bordercrossing_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de passeport')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('risk_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Critique / Interdiction')], default='MEDIUM', max_length=10)),
                ('reason', models.TextField(verbose_name='Motif de mise sous surveillance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Liste de surveillance',
                'verbose_name_plural': 'Liste de surveillance',
                'db_table': 'watchlist',
                'indexes': [models.Index(fields=['full_name'], name='watchlist_full_na_b2bfb8_idx'), models.Index(fields=['passport_number'], name='watchlist_passpor_c3bde5_idx')],
            },
        ),
    ]
