# Generated by Django 5.0 on 2026-02-21 10:36

import apps.biometrics.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("visa_applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "face_image",
                    models.ImageField(
                        upload_to=apps.biometrics.models.biometric_upload_path,
                        verbose_name="Photo faciale",
                    ),
                ),
                (
                    "face_encoding",
                    models.JSONField(default=dict, verbose_name="Encodage facial"),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Score qualité"
                    ),
                ),
                (
                    "liveness_verified",
                    models.BooleanField(
                        default=False, verbose_name="Vivacité vérifiée"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, verbose_name="Vérifié par agent"
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_data",
                        to="visa_applications.visaapplication",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_biometrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Données biométriques",
                "db_table": "evisa_biometric",
            },
        ),
    ]
