# Generated by Django 5.0 on 2026-03-31 12:32

import apps.biometrics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdata',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.biometrics.models.biometric_upload_path, verbose_name='Photo Passeport'),
        ),
    ]
